name: Release Automation

on:
  push:
    branches:
      - development

jobs:
  release-plz:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAC_RELEASE_PAT }}
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.63.0 # TODO: make MSRV an CI environment variable
          targets: thumbv7em-none-eabihf
      - name: Proper PAC crates generation
        run: |
          python3 tools/pacs.py
      - name: Fire up `release-plz`
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.PAC_RELEASE_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
